'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Zap,Undo2,Trash2,Volume2,VolumeX,Maximize,PanelRightClose,PanelRightOpen,Cable,X,RotateCcw,Plus,HelpCircle} from 'lucide-react';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {solveCircuit,initialScene,validScene,type Scene,type Part,type Kind} from '@/lib/circuit';
const names:Record<Kind,string>={battery:'电池',bulb:'小灯泡',switch:'开关',motor:'小电机'};
const kinds:Kind[]=['battery','bulb','switch','motor'];
const positions={battery:'0% 0%',bulb:'100% 0%',switch:'0% 100%',motor:'100% 100%'};
const term=(p:Part,s:number)=>({x:p.x+(s===0?-51:54),y:p.y+30});
function Sprite({kind}:{kind:Kind}){const i=kinds.indexOf(kind);return <svg x="-100" y="-115" width="200" height="200" viewBox={`${i%2*512} ${Math.floor(i/2)*512} 512 512`} overflow="hidden" pointerEvents="none"><image href="/apparatus.png" width="1024" height="1024"/></svg>;}
export default function Home(){
 const [scene,setScene]=useState<Scene>(initialScene),[ready,setReady]=useState(false),[saved,setSaved]=useState(true),[history,setHistory]=useState<Scene[]>([]),[selected,setSelected]=useState<string|null>(null),[connecting,setConnecting]=useState<string|null>(null),[cursor,setCursor]=useState({x:500,y:300}),[cabinet,setCabinet]=useState(true),[clearOpen,setClearOpen]=useState(false),[sound,setSound]=useState(true),[help,setHelp]=useState(false),[notice,setNotice]=useState('');
 const svg=useRef<SVGSVGElement>(null),audio=useRef<AudioContext|null>(null),drag=useRef<{id:string;x:number;y:number;dx:number;dy:number;moved:boolean;before:Scene}|null>(null),live=useRef(scene);live.current=scene;
 const result=useMemo(()=>solveCircuit(scene),[scene]);
 useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();try{void Promise.resolve(ctx.registerTool({name:'read_circuit',description:'Read the current apparatus, connections and simulated currents without changing the desk.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected empty object');return{scene:live.current,...solveCircuit(live.current)};}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[]);
 useEffect(()=>{try{const data=JSON.parse(localStorage.getItem('little-circuit-v1')||'null');if(validScene(data))setScene(data);}catch{}setReady(true);},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem('little-circuit-v1',JSON.stringify(scene));setSaved(true);}catch{setSaved(false);}},[scene,ready]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(t);},[notice]);
 const remember=(before=live.current)=>setHistory(h=>[...h.slice(-29),structuredClone(before)]);
 function change(next:Scene){remember();setScene(next);}
 function beep(f=500){if(!sound)return;try{audio.current??=new AudioContext();void audio.current.resume();const o=audio.current.createOscillator(),g=audio.current.createGain();o.connect(g);g.connect(audio.current.destination);o.frequency.value=f;g.gain.setValueAtTime(.035,audio.current.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.current.currentTime+.08);o.start();o.stop(audio.current.currentTime+.09);}catch{}}
 function point(e:{clientX:number;clientY:number}){const m=svg.current?.getScreenCTM();if(!m)return{x:500,y:300};const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());return{x:p.x,y:p.y};}
 function add(kind:Kind){if(scene.parts.length>=24){setNotice('桌上已经有很多器材啦，先收起几件吧');return;}const i=scene.parts.length,p:Part={id:crypto.randomUUID(),kind,x:220+i%4*180,y:180+Math.floor(i/4)%2*220,closed:false};change({...scene,parts:[...scene.parts,p]});setSelected(p.id);beep();}
 function getTerm(t:string){const [id,s]=t.split(':');const p=scene.parts.find(p=>p.id===id);return p?term(p,Number(s)):null;}
 function connect(t:string){if(!connecting){setConnecting(t);const pos=getTerm(t);if(pos)setCursor(pos);beep(650);return;}if(connecting===t||scene.wires.some(w=>(w.a===connecting&&w.b===t)||(w.b===connecting&&w.a===t))){setConnecting(null);return;}if(scene.wires.length>=200){setNotice('导线太多啦，先收起一些吧');return;}change({...scene,wires:[...scene.wires,{id:crypto.randomUUID(),a:connecting,b:t}]});setConnecting(null);beep(800);}
 function remove(){if(!selected)return;change({parts:scene.parts.filter(p=>p.id!==selected),wires:scene.wires.filter(w=>w.id!==selected&&!w.a.startsWith(selected+':')&&!w.b.startsWith(selected+':'))});setSelected(null);setConnecting(null);}
 function undo(){const last=history.at(-1);if(!last)return;setScene(last);setHistory(h=>h.slice(0,-1));setConnecting(null);setSelected(null);}
 function toggle(p:Part){change({...scene,parts:scene.parts.map(a=>a.id===p.id?{...a,closed:!a.closed}:a)});beep(p.closed?360:700);}
 function down(e:React.PointerEvent,p:Part){if(e.button!==0)return;e.stopPropagation();setConnecting(null);setSelected(p.id);const pos=point(e);drag.current={id:p.id,x:pos.x,y:pos.y,dx:p.x-pos.x,dy:p.y-pos.y,moved:false,before:structuredClone(scene)};svg.current?.setPointerCapture(e.pointerId);}
 function move(e:React.PointerEvent){const pos=point(e);setCursor(pos);const d=drag.current;if(!d)return;if(Math.hypot(pos.x-d.x,pos.y-d.y)>5)d.moved=true;if(d.moved)setScene(s=>({...s,parts:s.parts.map(p=>p.id===d.id?{...p,x:Math.max(100,Math.min(900,pos.x+d.dx)),y:Math.max(110,Math.min(540,pos.y+d.dy))}:p)}));}
 function up(e:React.PointerEvent){const d=drag.current;if(!d)return;drag.current=null;if(svg.current?.hasPointerCapture(e.pointerId))svg.current.releasePointerCapture(e.pointerId);if(d.moved)remember(d.before);else{const p=scene.parts.find(p=>p.id===d.id);if(p?.kind==='switch')toggle(p);}}
 const active=!result.short&&Object.values(result.currents).some(i=>Math.abs(i)>.003),chosen=scene.parts.find(p=>p.id===selected),start=connecting?getTerm(connecting):null;
 return <main className="lab dark"><header className="topbar"><div className="brand"><span className="brand-icon"><Zap size={23} fill="currentColor"/></span><div><h1>小小电路实验室</h1><span className="brand-sub">自由实验台</span></div></div><div className="save-state"><i/>{saved?'桌面已保存':'暂时无法保存'}</div><nav aria-label="桌面工具"><button onClick={undo} disabled={!history.length} title="撤销"><Undo2/><span>撤销</span></button><button onClick={()=>setClearOpen(true)} title="清空桌面"><Trash2/><span>清桌</span></button><span className="divider"/><button onClick={()=>setSound(!sound)} title={sound?'关闭声音':'打开声音'}>{sound?<Volume2/>:<VolumeX/>}<span>声音</span></button><button onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen?.().catch(()=>setNotice('当前浏览器暂不支持全屏'));}} title="全屏"><Maximize/><span>全屏</span></button></nav></header>
 <section className={'workspace '+(!cabinet?'cabinet-hidden':'')}><div className="work-area"><div className="desk-caption"><span className="desk-dot"/>电路 · 自由搭建</div><button className="cabinet-toggle" onClick={()=>setCabinet(!cabinet)} aria-label={cabinet?'收起器材柜':'打开器材柜'}>{cabinet?<PanelRightClose/>:<PanelRightOpen/>}</button>
 <svg ref={svg} viewBox="0 0 1000 660" className="desk" aria-label="自由电路实验桌" onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{if(drag.current)setScene(drag.current.before);drag.current=null;}} onPointerDown={e=>{if(e.target===e.currentTarget){setSelected(null);setConnecting(null);}}}>
 <defs><radialGradient id="bulbGlow"><stop offset="0" stopColor="#fff2bd" stopOpacity=".95"/><stop offset=".25" stopColor="#ffcf6b" stopOpacity=".55"/><stop offset="1" stopColor="#f9b845" stopOpacity="0"/></radialGradient><clipPath id="fanClip"><circle cx="0" cy="-40" r="61"/></clipPath><clipPath id="motorBase"><path d="M-100 -115H100V85H-100Z M-61 -101V21H61V-101Z" clipRule="evenodd"/></clipPath><clipPath id="switchBase"><rect x="-100" y="-16" width="200" height="101"/></clipPath><clipPath id="switchLever"><rect x="-100" y="-115" width="200" height="99"/></clipPath></defs>
 {scene.wires.map(w=>{const a=getTerm(w.a),b=getTerm(w.b);if(!a||!b)return null;const d=`M${a.x},${a.y} C${a.x},${a.y+70} ${b.x},${b.y+70} ${b.x},${b.y}`;return <g key={w.id} className="wire" role="button" tabIndex={0} aria-label="导线，点击选中后可移除" onClick={()=>{setSelected(w.id);setConnecting(null);}} onKeyDown={e=>{if(e.key==='Enter')setSelected(w.id);}}><path d={d} stroke="transparent" strokeWidth="25" fill="none"/><path d={d} stroke="#121922" strokeWidth="8" fill="none"/><path d={d} stroke={selected===w.id?'#79d7ef':'#a6b2bf'} strokeWidth="4" fill="none"/><path d={d} stroke="#e4ebf2" strokeOpacity=".4" strokeWidth="1" fill="none"/></g>;})}
 {start&&<path d={`M${start.x},${start.y} Q${start.x},${start.y+60} ${cursor.x},${cursor.y}`} stroke="#79d5f4" strokeWidth="3" strokeDasharray="7 7" fill="none" pointerEvents="none"/>}
 {scene.parts.map(p=>{const current=result.short?0:result.currents[p.id]||0,powered=Math.abs(current)>.003;return <g key={p.id} transform={`translate(${p.x},${p.y})`} className={'apparatus '+(selected===p.id?'selected':'')}><rect x="-94" y="-103" width="188" height="191" rx="20" className="selection-ring"/><g role="button" tabIndex={0} aria-label={names[p.kind]+(p.kind==='switch'?(p.closed?'，已合上':'，已断开'):'，拖动摆放')} onPointerDown={e=>down(e,p)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();if(p.kind==='switch')toggle(p);else setSelected(p.id);}if(e.key.startsWith('Arrow')){e.preventDefault();change({...scene,parts:scene.parts.map(a=>a.id===p.id?{...a,x:Math.max(100,Math.min(900,a.x+(e.key==='ArrowRight'?15:e.key==='ArrowLeft'?-15:0))),y:Math.max(110,Math.min(540,a.y+(e.key==='ArrowDown'?15:e.key==='ArrowUp'?-15:0)))}:a)});}}}><rect x="-95" y="-105" width="190" height="175" fill="transparent"/>
 {p.kind==='motor'?<><g clipPath="url(#motorBase)"><Sprite kind={p.kind}/></g><g className={powered?'rotor':''} style={{animationDuration:`${Math.max(.18,1/(Math.abs(current)*15))}s`,animationDirection:current>0?'normal':'reverse'}}><g clipPath="url(#fanClip)"><Sprite kind={p.kind}/></g></g></>:p.kind==='switch'?<><g clipPath="url(#switchBase)"><Sprite kind={p.kind}/></g><g transform={p.closed?'rotate(34 -40 -22)':''}><g clipPath="url(#switchLever)"><Sprite kind={p.kind}/></g></g></>:<g transform={p.kind==='battery'?'scale(-1 1)':''}><Sprite kind={p.kind}/></g>}
 {p.kind==='bulb'&&powered&&<ellipse cx="0" cy="-53" rx="77" ry="86" fill="url(#bulbGlow)" opacity={Math.min(1,Math.abs(current)/.18)} pointerEvents="none"/>}</g>
 {[0,1].map(side=><g key={side} transform={`translate(${side===0?-51:54},30)`} role="button" tabIndex={0} aria-label={`${names[p.kind]}${side===0?'蓝色':'红色'}接线柱`} className={'terminal '+(connecting===`${p.id}:${side}`?'pending':'')} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();connect(`${p.id}:${side}`);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();connect(`${p.id}:${side}`);}}}><circle r="25" fill="transparent"/><circle r="11" fill={side===0?'#288bbc':'#c7515b'} stroke="#d9e9f0" strokeOpacity=".7" strokeWidth="1.5"/><circle r="5" fill="#17212b"/><circle className="terminal-halo" r="20" fill="none" stroke="#9fe8ff" strokeWidth="2"/></g>)}
 <text y="92" className="part-name" textAnchor="middle">{names[p.kind]}{p.kind==='battery'?' · 1.5 V':''}</text>{p.kind==='switch'&&<text y="114" className="part-status" textAnchor="middle">{p.closed?'已合上':'点一下合上'}</text>}{p.kind==='motor'&&powered&&<text y="114" className="part-status" textAnchor="middle">{current>0?'顺时针转动':'逆时针转动'}</text>}</g>;})}
 {!scene.parts.length&&<text x="500" y="310" textAnchor="middle" className="empty-desk">从右边拿一件器材，开始吧</text>}</svg>
 <div className="desk-bottom"><button className="help-button" onClick={()=>setHelp(!help)} aria-label="操作提示"><HelpCircle size={20}/></button><span className="hint">{connecting?'再点另一个接线柱，即可连起来':'拖动器材 · 点接线柱连线'}</span><span className={'circuit-state '+(result.short?'warning':active?'running':'')}>{result.short?'短路啦，电池已暂停供电':active?'电路正在工作':'等待接通'}</span></div>
 {selected&&<div className="selection-tools"><span>{chosen?names[chosen.kind]:'导线'}</span>{chosen?.kind==='switch'&&<button onClick={()=>toggle(chosen)}><Zap size={17}/>{chosen.closed?'断开':'合上'}</button>}<button onClick={remove}><Trash2 size={17}/>收起来</button><button onClick={()=>setSelected(null)} aria-label="取消选择"><X size={18}/></button></div>}
 {help&&<div className="help-card"><button onClick={()=>setHelp(false)} aria-label="关闭提示"><X size={18}/></button><h2>像在桌上玩一样</h2><p>① 点右边的器材，把它拿出来。</p><p>② 拖动器材，放到喜欢的位置。</p><p>③ 先点一个接线柱，再点另一个。</p><p>④ 点一下开关，看看会发生什么。</p><small>点选器材或导线，再点“收起来”即可移除。</small></div>}</div>
 {cabinet&&<aside className="cabinet"><div className="cabinet-heading"><h2>实验器材</h2><span>点一下拿出来</span></div><div className="cabinet-category"><Zap size={16}/>基础电路<span>4</span></div><div className="parts-grid">{kinds.map(k=><button key={k} className="part-card" onClick={()=>add(k)}><span className="add-icon"><Plus size={15}/></span><span className="part-image" style={{backgroundPosition:positions[k]}}/><span>{names[k]}</span><small>{k==='battery'?'1.5 V':k==='bulb'?'亮起来':k==='switch'?'接通 · 断开':'转起来'}</small></button>)}</div><div className="wire-note"><Cable size={22}/><div><strong>导线随手连</strong><p>点两个接线柱就能接线</p></div></div><button className="example-button" onClick={()=>{change(initialScene());setSelected(null);setConnecting(null);}}><RotateCcw size={17}/>摆好一组电路</button><div className="cabinet-foot"><i/>自由探索，没有标准答案</div></aside>}</section>
 {notice&&<div className="notice" role="status">{notice}</div>}<AlertDialog open={clearOpen} onOpenChange={setClearOpen}><AlertDialogContent><AlertDialogTitle>把桌面收拾干净？</AlertDialogTitle><AlertDialogDescription>所有器材和导线都会收起，还可以点“撤销”找回来。</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>继续玩</AlertDialogCancel><AlertDialogAction onClick={()=>{change({parts:[],wires:[]});setSelected(null);setConnecting(null);setClearOpen(false);}}>收拾桌面</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></main>;
}
